feat(perfomance): increase drawer perfromance
budproj/execution-mode pull request #216
Opened 2022-03-03 17:37 UTC by guiluchesi

## ☕ Purpose

This PR intend to update to increase the performance of the content drawer

## 🧐 Checklist

- [x] Increase the performance of the content drawer

## 🐞 Testing

Record the performance (web inspector tab) of the opening drawer on both branches and compare the numbers between them.

## 🍩 Further details

I detected that a great part of the issue was the skeleton component animation was making the render calculation way harder because the drawer was transitioning throughout the screen so it had to be recalculated every time it changed position.

So after a few tests, I found out that removing the skeleton had the best performance increase without changing too much on the code. I've recorded three of these tests and compared them. We've got an average increase of 35% in scripting and 43% in rendering.

![image](https://user-images.githubusercontent.com/5860206/156619060-d9649098-cd57-4aeb-8f0b-14baaa60a3e2.png)

2022-03-03 19:28 UTC, delucca requested changes
So checa a questao do portal, se estiver ok pode fazer o merge

2022-03-03 19:28 UTC, delucca commented on src/components/KeyResult/Single/Drawer/Body/body.tsx
> -      <Portal containerRef={timelinePortalReference}>
Você consegue testar uma coisa nesse caso por favor? Tenta ir num KR com comentários, e abre o popover pra alterar o dono. Esse portal existia pra impedir que o popover de alterar dono ficasse por baixo dos cards da timeline

2022-03-03 19:28 UTC, delucca commented on src/components/KeyResult/Single/Sections/Checklist/wrapper.tsx
> +        ''
Não seria melhor colocar um Fragment ou null?

2022-03-04 03:06 UTC, guiluchesi commented on src/components/KeyResult/Single/Sections/Checklist/wrapper.tsx
> +        ''
Massa! Não sabia que tinha diferença entre string vazia e null haha atualizei aqui e no outro arquivo que retornava string também.

2022-03-04 03:08 UTC, guiluchesi commented on src/components/KeyResult/Single/Drawer/Body/body.tsx
> -      <Portal containerRef={timelinePortalReference}>
Ah, saquei, só reverti o commit então. Não era um fator de performance, só me pareceu meio bizarro e não tinha mudado o comportamento nos meus testes então mantive, mas como tem esse caso específico, melhor manter.

2022-03-04 12:51 UTC, delucca commented on src/components/KeyResult/Single/Drawer/Body/body.tsx
> -      <Portal containerRef={timelinePortalReference}>
É, portal é meio bizarro mesmo xD

Boa!

2022-03-04 12:51 UTC, delucca approved these changes
LGTM

2022-03-04 12:51 UTC, merged