Feat/dashboard strategy health
budproj/execution-mode pull request #255
Opened 2022-04-27 17:40 UTC by rodrigoantas

## ☕ Purpose

A brief summary about the purpose of this PR.

## 🧐 Checklist

- [x] A feature that will work with this PR
- [ ] A feature that I'm still working on

## 🐞 Testing

A brief description about how the reviewer can test my PR.

~~~shell
# don't forget to insert cli commands
~~~

## 🍩 Further details

Anything that the reviewer should know before approving it.

## 🔗 Related PRs

This PR is related to some other PRs in different services, they are:
* [`project#PR_NUMBER`](https://)

2022-04-27 17:42 UTC, guiluchesi commented
Alinhar com o Gustavo/Marcelo sobre o skeleton e as porcentagens (math.round está tendo cenários de +100%, por exemplo).

2022-04-28 14:26 UTC, victorperin requested changes
Mudanças importantes:

- [x] simplificar implementação de texto de loading a algo próximo à sugestão que dei
- [x] reusar `interface Confidence`
- [x] tentar reusar `getConfidanceQuantities`
- [x] remover arquivo em branco `src/components/Report/BoardsOverview/KeyResultConfidences/messages.ts`
- [ ] remover arquivo `src/components/Report/BoardsOverview/queries.gql`
- [ ] simplificar import `hooks/getHealthConfidenceQuantities`

Além dessas pequenas mudanças que não atrapalham o deploy (mas seriam interessantes de serem resolvidas), você conseguiu implementar uma feature bastante requisitada pelos usuários de maneira rápida. Parabéns! :tada:  :tada:  :tada:

2022-04-28 14:26 UTC, victorperin commented on src/components/Report/BoardsOverview/KeyResultConfidences/constants.tsx
> +}
Essa interface está sendo usada em 3 lugares diferentes. O que você acha de importa-la?
Pode ser exportada aqui ou em qualquer outro arquivo, mas é importante que ela seja definida apenas 1 vez.

2022-04-28 14:26 UTC, victorperin commented on src/components/Report/BoardsOverview/StackedProgressBar/index.tsx
> +  }
Essa função `getConfidanceQuantities` existe em um outro arquivo e me parece bem próxima. Será que existe a possibilidade de reusarmos?

2022-04-28 14:26 UTC, victorperin commented on src/components/Report/BoardsOverview/queries.gql
> +}
Essa query não é executada nunca, além disso, existe uma query exatamente igual, chamada `GET_HEALTH_CONFIDENCE_QUANTITIES`. 

Minha sugestão é remover todo esse arquivo.

2022-04-28 14:26 UTC, victorperin commented on src/components/Report/BoardsOverview/KeyResultConfidences/constants.tsx
> +}
Outra sugestão: usar o arquivo `src/components/Team/types.ts` ou criar um arquivo types nesse contexto.

2022-04-28 17:38 UTC, rodrigoantas commented on src/components/Report/BoardsOverview/Board/index.tsx
> +      )}
ótimo! bem melhor. testei e funcionou da mesma maneira.

2022-04-28 17:41 UTC, rodrigoantas commented on src/components/Report/BoardsOverview/KeyResultConfidences/constants.tsx
> +}
achei melhor deixar neste arquivo de constants, mover o arquivo constants para cima (já que é usado por todo o componente) e deixar a exportação somente neste arquivo.

2022-04-28 17:43 UTC, rodrigoantas commented on src/components/Report/BoardsOverview/KeyResultConfidences/constants.tsx
> +}
na verdade, olhando as outras sugestões achei melhor criar um arquivo types e separa-lo de constants.

2022-04-28 17:46 UTC, rodrigoantas commented on src/components/Report/BoardsOverview/StackedProgressBar/index.tsx
> +  }
sim! coloquei ela no arquivo de constants :)

2022-04-28 17:48 UTC, rodrigoantas commented on src/components/Report/BoardsOverview/queries.gql
> +}
feito.

2022-04-28 17:48 UTC, rodrigoantas commented on src/components/Report/BoardsOverview/index.tsx
> +import { useGetHealthConfidenceQuantities } from '../hooks/getHealthConfidenceQuantities/index'
feito.

2022-05-05 14:04 UTC, victorperin approved these changes

2022-05-05 14:04 UTC, merged

2022-05-05 14:04 UTC, guiluchesi approved these changes